spring.application.name=wallet-backend
server.port=${SERVER_PORT:10000}
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/wallet_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health,info,metrics,prometheus
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-minutes=120
app.transfer.daily-limit=2000.00
app.sandbox.topup-enabled=false
